name = "Perdido"
author = "GregRos"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba62e3b3d1df1379269708d64f26887cd624787a220e6256eaef38554c82ec7a"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.19.4", "1.20", "1.94.4"]
