name = "Perdido"
author = "GregRos"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16ccf4d59e5f7419de233df3538aa6a079f3fc1bc4ebea52cd92f733309c35f7"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.19.4", "1.20", "1.94.4"]
